### ISSUE TITLE
Exception in layout editor

### ISSUE THREAD

**Issue by weirdgyn** [eo/signal-strength-view#1]
When I try to use this component I always get this message in layout editor:

> The following classes could not be instantiated:
> - eo.view.signalstrength.SignalStrengthView (Open Class, Show Exception, Clear Cache)
>  Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.

This's the exception I got:
```
android.content.res.Resources$NotFoundException: Resource ID #0x7f090000
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
	at android.content.res.Resources.getFraction(Resources.java:776)
	at eo.view.signalstrength.SignalStrengthDrawable.<init>(SignalStrengthDrawable.kt:29)
	at eo.view.signalstrength.SignalStrengthView.<init>(SignalStrengthView.kt:56)
	at eo.view.signalstrength.SignalStrengthView.<init>(SignalStrengthView.kt:12)
	at eo.view.signalstrength.SignalStrengthView.<init>(SignalStrengthView.kt)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:404)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:187)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:145)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:309)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:417)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:428)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:332)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1123)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1097)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:501)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:328)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:396)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:209)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:608)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$6(RenderTask.java:734)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

this's the xml code:

`    <eo.view.signalstrength.SignalStrengthView
        android:id="@+id/gcs_signal_level"
        android:layout_width="50dp"
        android:layout_height="50dp"
        app:layout_constraintEnd_toStartOf="@+id/gcs_battery_level"
        app:layout_constraintTop_toTopOf="parent"
        app:signalStrengthColor="?colorAccent"
        app:signalStrengthLevel="50"
        app:signalStrengthTheme="rounded" />`

BTW I'm using battery-meter-view in the same project and it works fine.
The sample application is working.

**Comment by weirdgyn** [comment]
the sample application is working.

**Comment by Elswah** [comment]
how did you solve it @weirdgyn

**Comment by weirdgyn** [comment]
> how did you solve it @weirdgyn

hi @Elswah .... I designed one on my own.

**Comment by Elswah** [comment]
@weirdgyn  could you share the custom view with me

**Comment by weirdgyn** [comment]
@Elswah:

package it.robint.tux.components;

import android.content.Context;
import android.content.res.TypedArray;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.PorterDuff;
import android.util.AttributeSet;
import android.view.View;

import androidx.annotation.Nullable;

import java.util.Locale;

import it.robint.tux.components.R;

public class SignalStrengthView extends View {
    private static final float DEF_FRAME_RATIO = 0.9f;
    private static final int FRAME_RADIUS_RATIO = 10;
    private static final int DEF_TEXT_RATIO = 2;
    private static final int DEF_STROKE_WIDTH = 1;
    private static final float DEF_TEXT_SIZE = 20f;
    private static final float WARN_TEXT_SIZE = 80f;
    private static final int DEF_MIN_HEIGHT_FOR_TEXT = 70;
    private static final int DEF_COLOR = Color.BLUE;
    private static final int DEF_FILL_COLOR = Color.BLUE;
    private static final int DEF_TEXT_COLOR = Color.WHITE;
    private static final int DEF_WARN_COLOR = Color.YELLOW;
    private static final int DEF_SAFE_COLOR = Color.GREEN;
    private static final String MODEM_FAILURE = "!";
    private static final String LINK_FAILURE = "x";
    private static final int DEF_SAFE_LEVEL = 66;
    private static final int DEF_WARN_LEVEL = 25;

    private int mLevel;
    private int mSafeLevel;
    private int mWarnLevel;
    private Paint mFillPaint;
    private Paint mFramePaint;
    private Paint mTextPaint;
    private Path mFramePath;
    private Path mFillPath;
    private boolean mShowLevelText;
    private int mFrameColor;
    private int mFillColor;
    private int mSafeFillColor;
    private int mTextColor;
    private int mWarnFillColor;
    private boolean mLinkFailure;
    private boolean mModemFailure;

    public SignalStrengthView(Context context) {
        super(context);
        init(null);
    }

    public SignalStrengthView(Context context, @Nullable AttributeSet attrs) {
        super(context, attrs);
        init(attrs);
    }

    public SignalStrengthView(Context context, @Nullable AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init(attrs);
    }

    public void init(@Nullable AttributeSet attrs) {
        mTextPaint = new Paint();
        mTextPaint.setAntiAlias(true);
        mTextPaint.setColor(Color.WHITE);
        mTextPaint.setTextAlign(Paint.Align.CENTER);
        mTextPaint.setTextSize(DEF_TEXT_SIZE);
        // TODO: text size should be function of mHeight

        mFramePaint = new Paint();
        mFramePaint.setAntiAlias(true);
        mFramePaint.setStrokeWidth(DEF_STROKE_WIDTH);
        mFramePaint.setStyle(Paint.Style.FILL_AND_STROKE);
        mFramePaint.setColor(DEF_COLOR);

        mFillPaint = new Paint();
        mFillPaint.setAntiAlias(true);
        mFillPaint.setStrokeWidth(DEF_STROKE_WIDTH);
        mFillPaint.setStyle(Paint.Style.FILL_AND_STROKE);
        mFillPaint.setColor(DEF_FILL_COLOR);

        mFillPath = new Path();
        mFillPath.setFillType(Path.FillType.EVEN_ODD);

        mFramePath = new Path();
        mFramePath.setFillType(Path.FillType.EVEN_ODD);

        // Default values
        mFrameColor = DEF_COLOR;
        mFillColor = DEF_FILL_COLOR;
        mTextColor = DEF_TEXT_COLOR;
        mWarnFillColor = DEF_WARN_COLOR;
        mSafeFillColor = DEF_SAFE_COLOR;
        mShowLevelText = false;
        mLinkFailure = false;
        mModemFailure = false;
        mLevel = 100;
        mSafeLevel = DEF_SAFE_LEVEL;
        mWarnLevel = DEF_WARN_LEVEL;
        //

        if (attrs != null) {
            final TypedArray attributes = getContext().obtainStyledAttributes(attrs,
                    R.styleable.SignalStrengthView,
                    0, 0);

            mFrameColor = attributes.getColor(R.styleable.SignalStrengthView_frameColor, mFrameColor);
            mShowLevelText = attributes.getBoolean(R.styleable.SignalStrengthView_showLevelText, mShowLevelText);
            mTextColor = attributes.getColor(R.styleable.SignalStrengthView_levelTextColor, mTextColor);
            mLevel = attributes.getInt(R.styleable.SignalStrengthView_level, mLevel);
            mSafeLevel = attributes.getInt(R.styleable.SignalStrengthView_safeLevel, mSafeLevel);
            mWarnLevel = attributes.getInt(R.styleable.SignalStrengthView_warnLevel, mWarnLevel);
            mFillColor = attributes.getColor(R.styleable.SignalStrengthView_fillColor, mFillColor);
            mWarnFillColor = attributes.getColor(R.styleable.SignalStrengthView_warnFillColor, mWarnFillColor);
            mSafeFillColor = attributes.getColor(R.styleable.SignalStrengthView_safeFillColor, mSafeFillColor);
            mLinkFailure = attributes.getBoolean(R.styleable.SignalStrengthView_linkFailure, mLinkFailure);
            mModemFailure = attributes.getBoolean(R.styleable.SignalStrengthView_modemFailure, mModemFailure);

            mFramePaint.setColor(mFrameColor);

            attributes.recycle();
        }

        setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                invalidate();
            }
        });
    }

    @Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);

        final int mWidth = getMeasuredWidth();
        final int mHeight = getMeasuredHeight();
        final float _fillw = mWidth * (mLevel) / 100f;
        final float _fillh = mHeight * (100f - mLevel) / 100f;

        canvas.drawColor(Color.TRANSPARENT);

        mFramePath.reset();
        mFillPath.reset();

        if (mLevel < mWarnLevel)
            mFillPaint.setColor(mWarnFillColor);
        else if ((mLevel >= mWarnLevel) && (mLevel < mSafeLevel))
            mFillPaint.setColor(mFillColor);
        else if (mLevel >= mSafeLevel)
            mFillPaint.setColor(mSafeFillColor);

        mFramePath.moveTo(0, mHeight);
        mFramePath.lineTo(mWidth, mHeight);
        mFramePath.lineTo(mWidth, 0);
        mFramePath.close();

        mFillPath.moveTo(0, mHeight);
        mFillPath.lineTo(_fillw, mHeight);
        mFillPath.lineTo(_fillw, _fillh);
        mFillPath.close();

        canvas.drawPath(mFramePath, mFramePaint);
        canvas.drawPath(mFillPath, mFillPaint);

        if (Math.min(mWidth, mHeight) > DEF_MIN_HEIGHT_FOR_TEXT) {
            final float _x = (mWidth / 2f);
            final float _y = (mHeight / 2f) - ((mTextPaint.descent() + mTextPaint.ascent()) / 2);

            mTextPaint.setColor(mTextColor);

            if (mModemFailure) {
                mTextPaint.setTextSize(WARN_TEXT_SIZE);
                canvas.drawText(MODEM_FAILURE, _x, _y, mTextPaint);
            } else if (mLinkFailure) {
                mTextPaint.setTextSize(WARN_TEXT_SIZE);
                canvas.drawText(LINK_FAILURE, _x, _y, mTextPaint);
            } else if (mShowLevelText)
                canvas.drawText(String.format(Locale.getDefault(), "%d%%", mLevel), _x, _y, mTextPaint);
        }
    }

    @SuppressWarnings("unused")
    public int getLevel() {
        return mLevel;
    }

    @SuppressWarnings("unused")
    public void setLevel(int level) {
        if (this.mLevel != level) {
            this.mLevel = level;
            invalidate();
        }
    }

    @SuppressWarnings("unused")
    public boolean getLinkFailure() {
        return mLinkFailure;
    }

    @SuppressWarnings("unused")
    public void setLinkFailure(boolean link_failure) {
        if (this.mLinkFailure != link_failure) {
            this.mLinkFailure = link_failure;
            invalidate();
        }
    }

    @SuppressWarnings("unused")
    public boolean getModemFailure() {
        return mModemFailure;
    }

    @SuppressWarnings("unused")
    public void setModemFailure(boolean modem_failure) {
        if (this.mModemFailure != modem_failure) {
            this.mModemFailure = modem_failure;
            invalidate();
        }
    }
}

**Comment by weirdgyn** [comment]
I have some problem in copy pasting code here ... and the repository of the project where I'm using it is private.
I'm sharing this .java files trough google drive:

https://drive.google.com/file/d/1017Kv8G9y_ysMIIVfsWQlhAYfRAUmIC-/view?usp=sharing

**Comment by Elswah** [comment]
@weirdgyn  could you please share it again
